#!/usr/bin/python3
"""
using the 5-save_to_json_file and 6-load_from_json_file modules
"""
import json
import sys
save_to_json_file = __import__("5-save_to_json_file").save_to_json_file
load_from_json_file = __import__("6-load_from_json_file").load_from_json_file

with open("add_item.json", "w+", encoding="utf-8") as f:
    if f.read() == 0:
        j_list = []
    else:
        j_list = load_from_json_file("add_item.json")

for i in range(len(argv - 1)):
    x = argv[i + 1]
    j_list.append(x)
with open("add_item.json", "a", encoding="utf-8") as f:
    save_to_json_file(j_list, "add_item.json")
